### PR TITLE
Support for Nette 3.0

### LINKED ISSUE #15: Support for Nette 3.0
Please add support for Nette 3.0.

### PR DESCRIPTION
**Pull request by KacerCZ**
* updated dependencies
* updated implementations of HTTP request and response classes
* ignore some errors reported by PHPStan

Closes #15

### CODE REVIEW

**Comment by f3l1x** [comment]
Excellent.

**Comment by KacerCZ** [comment]
@f3l1x Can you please make release containig this PR.

**Comment by f3l1x** [comment]
Are you OK with v1.2.0?

**Comment by KacerCZ** [comment]
Yes.

**Comment by f3l1x** [comment]
Bumped.

**Comment by KacerCZ** [comment]
Thanks.

**Pull request merged**
